### ISSUE TITLE
Error in datafeeder.py

### ISSUE THREAD

**Issue by shrinidhin** [syang1993/gst-tacotron#37]
Traceback (most recent call last):   File "/speech/Demo/gst-tacotron-master/datasets/datafeeder.py", line 75, in run     self._enqueue_next_group()   File "/speech/Demo/gst-tacotron-master/datasets/datafeeder.py", line 87, in _enqueue_next_group     examples = [self._get_next_example() for i in range(n * _batches_per_group)]   File "/speech/Demo/gst-tacotron-master/datasets/datafeeder.py", line 87, in <listcomp>     examples = [self._get_next_example() for i in range(n * _batches_per_group)]   File "/speech/Demo/gst-tacotron-master/datasets/datafeeder.py", line 105, in _get_next_example     meta = self._metadata[self._offset] IndexError: list index out of range

I got the above error in datafeeder.py when i ran the train.py file. I initially got an Incompatible shapes error so I increased the max_iters parameter from 1000 to 2000.
What changes should I do to resolve the above error?

**Comment by shrinidhin** [comment]
I have resolved the issue. It was an issue with the size of my input data.
